spring.application.name=storage-node
server.port=8080

# Multipart Upload Configurations (Max size: 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# TitanFS Self-Registration and Heartbeat Settings
titanfs.metadata.server.url=http://localhost:8081
titanfs.node.host=localhost
titanfs.node.port=${server.port}
titanfs.node.id=storage-node-default
